#!/usr/bin/env bash
set -euo pipefail

# if we are executing in a package that has lazyrepo installed, use that

if [ -f node_modules/lazyrepo/src/cli.ts ]; then
  node --loader tsx --no-warnings node_modules/lazyrepo/src/cli.ts "$@"
  exit 0
fi

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

node --loader tsx --no-warnings $DIR/src/cli.ts "$@"