name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: 'Lint and Test'
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Lint
        if: ${{ matrix.os != 'windows-latest' }} 
        run: pnpm lint

      - name: format
        if: ${{ matrix.os != 'windows-latest' }} 
        run: pnpm format:check

      - name: Typecheck
        if: ${{ matrix.os != 'windows-latest' }} 
        run: pnpm tsc

      - name: Test
        if: ${{ matrix.os != 'windows-latest' }} 
        run: pnpm test

      - name: Test (windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: pnpm test -- --runInBand


